### ISSUE TITLE
Error: No native build was found for platform

### ISSUE THREAD

**Issue by chandirag** [yao-pkg/pkg#66]
### What version of pkg are you using?

5.10.0

### What version of Node.js are you using?

18.18.2

### What operating system are you using?

Ubuntu 22.04.4 LTS

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node18-linuxstatic-armv7

### Describe the Bug

My project uses the [node-serialport](https://www.npmjs.com/package/serialport) library. I am getting the following error when trying to run the compiled binary:
```
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: No native build was found for platform=linux arch=arm runtime=node abi=108 uv=1 armv=default libc=glibc node=18.18.2
    loaded from: /snapshot/my-project/node_modules/@serialport/bindings-cpp

    at Function.<anonymous> (/snapshot/my-project/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/snapshot/my-project/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/snapshot/my-project/node_modules/@serialport/bindings-cpp/dist/load-bindings.js:11:46)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:119:18)

Node.js v18.18.2
```

I also get the following warning during compilation (when running `npm run package`):
```
> pkg@5.10.0
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=armv7 libc= platform=undefined)
prebuild-install warn install No prebuilt binaries found (target=v18.18.2 runtime=node arch=armv7 libc= platform=undefined)
```

I have the following package.json:
```
{
	"name": "my-project",
	"version": "0.0.1",
	"description": "",
	"bin": "dist/src/main.js",
	"scripts": {
		"build": "nest build",
		"format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
		"start": "nest start",
		"package": "npm run build && mkdir -p bin && npx pkg ."
	},
	"dependencies": {
		"@nestjs/common": "^10.0.0",
		"@nestjs/config": "^3.2.2",
		"@nestjs/core": "^10.0.0",
		"@nestjs/platform-express": "^10.0.0",
		...
		"serialport": "^10.5.0",
	},
	"devDependencies": {
		"@nestjs/cli": "^10.0.0",
		"@nestjs/schematics": "^10.0.0",
		"@nestjs/testing": "^10.3.8",
		...
	},
	"pkg": {
		"scripts": "dist/**/*.js",
		"targets": [
			"node18-linuxstatic-armv7"
		],
		"assets": [
			"./node_modules/@serialport/bindings-cpp/**"
		],
		"outputPath": "bin"
	}
}
```

What I've already tried:
- Downgrading serialport. Tried the latest (v12.0.0) as well as older versions (v10.5.0)
- Tried adding the following under pkg "assets" ([#61](https://github.com/yao-pkg/pkg/issues/61), [#1903](https://github.com/vercel/pkg/issues/1903), [#1660](https://github.com/vercel/pkg/issues/1660)):
     - "./node_modules/@serialport/bindings-cpp/**"
     - "./node_modules/@serialport/bindings-cpp/prebuilds",
     - "./node_modules/@serialport/**/*"
- I also tried copying the prebuilds directory to the same directory as the output 'bin/' [#1660](https://github.com/vercel/pkg/issues/1660)

I still keep getting the above error. Any help is appreciated.

### Expected Behavior

Compiled binary to execute without throwing `Error: No native build was found for platform=linux arch=arm runtime=node abi=108 uv=1 armv=default libc=glibc node=18.18.2`

### To Reproduce

Compiling any new node project which utilizes the serial port library
- Serialport v12.0.0
- pkg v5.10.0
- node v18.18.2

**Comment by DaniRey** [comment]
Totally forgot to mention. We also build a Windows version, which works like a charm.

What also works is copying the `target\transpiled` folder to a RaspberryPi and running it with a pre-installed node version. 

Therefore I assume it is either an issue with the pre-built node executable, or with the selection of the correct pre-built version of serialport.

This is an extract of our package.json

```
  "bin": "target/transpiled/bundle.cjs",
  "pkg": {
    "targets": [
      "node22-win-x64",
      "node22-linuxstatic-arm64",
      "node22-linuxstatic-armv7"
    ],
    "assets": [
      "target/transpiled",
      "node_modules/node-gyp-build/**",
      "node_modules/@serialport/bindings-cpp/**"
    ],
    "outputPath": "target/bin"
  },
  "scripts": {
    "dev": "nodemon -x tsx src/main.ts",
    "serve": "node target/transpiled/bundle.cjs",
    "vite": "vite",
    "build": "vite build --emptyOutDir --mode production",
    "roll": "rollup --config",
    "dist-win": "pkg . --no-bytecode --public-packages \"*\" --public --debug -C GZip",
    "dist": "npm run build && npm run roll && npm run dist-win"
  }
```

**Comment by robertsLando** [comment]
Please share pkg command output with `--debug` flag. Then run the result package with `DEBUG_PKG=2` env var and share the run output as well

Does this happens also with older pkg versions?

**Comment by DaniRey** [comment]
@robertsLando that's the full log, I started the application from the desktop.

The trick with patching should get us going. I'll use it to add some additional logging and then hopefully to patch require the way we need it. I too suspect that this is where the problem lays.

I'll try it after the holidays. Thank you for the support.

**Comment by DaniRey** [comment]
Ok, we're making progress. Here is a minimal project setup https://github.com/DaniRey/pkg_serialport_friendship

The reason the native serialport module is not found, is that "armv" is set to "default" in node22_linuxstatic_armv7.

When I modify node_modules/node-gyp-build/node-gyp-build.js and add the following line (plus some logging).

` if (armv === "default") armv = "7"`

the lookup works, but unfortunately I then get ERR_DLOPEN_FAILED. By the way, the whole setup still works as expected on windows.

```
./pkg_serialport_friendship-linuxstatic-armv7 
Found tuple: android-arm with arch arm and platform android
Found tuple: android-arm64 with arch arm64 and platform android
Found tuple: darwin-x64+arm64 with arch x64,arm64 and platform darwin
Found tuple: linux-arm with arch arm and platform linux
Found tuple: linux-arm64 with arch arm64 and platform linux
Found tuple: linux-x64 with arch x64 and platform linux
Found tuple: win32-ia32 with arch ia32 and platform win32
Found tuple: win32-x64 with arch x64 and platform win32
Looking for tuple with platform linux and arch arm abi 127 runtime node uv 1 armv 7 libc glibc
Found prebuild: node.napi.armv6.node with tags {"file":"node.napi.armv6.node","specificity":3,"runtime":"node","napi":true,"armv":"6"}
Found prebuild: node.napi.armv7.node with tags {"file":"node.napi.armv7.node","specificity":3,"runtime":"node","napi":true,"armv":"7"}
going to call require with: /snapshot/pkg_serialport_friendship/node_modules/@serialport/bindings-cpp/prebuilds/linux-arm/node.napi.armv7.node
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Dynamic loading not supported
    at process.dlopen (pkg/prelude/bootstrap.js:2256:28)
    at Module._extensions..node (node:internal/modules/cjs/loader:1719:18)
    at Module.load (node:internal/modules/cjs/loader:1322:32)
    at Module._load (node:internal/modules/cjs/loader:1132:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1344:12)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/helpers:141:16)
    at load (/snapshot/pkg_serialport_friendship/node_modules/node-gyp-build/node-gyp-build.js:22:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v22.10.0
```

The fully modified version of node_modules/node-gyp-build/node-gyp-build.js is as follows

```
var fs = require('fs')
var path = require('path')
var os = require('os')

// Workaround to fix webpack's build warnings: 'the request of a dependency is an expression'
var runtimeRequire = typeof __webpack_require__ === 'function' ? __non_webpack_require__ : require // eslint-disable-line

var vars = (process.config && process.config.variables) || {}
var prebuildsOnly = !!process.env.PREBUILDS_ONLY
var abi = process.versions.modules // TODO: support old node where this is undef
var runtime = isElectron() ? 'electron' : (isNwjs() ? 'node-webkit' : 'node')

var arch = process.env.npm_config_arch || os.arch()
var platform = process.env.npm_config_platform || os.platform()
var libc = process.env.LIBC || (isAlpine(platform) ? 'musl' : 'glibc')
var armv = process.env.ARM_VERSION || (arch === 'arm64' ? '8' : vars.arm_version) || ''
var uv = (process.versions.uv || '').split('.')[0]

module.exports = load

function load (dir) {
  return runtimeRequire(load.resolve(dir))
}

load.resolve = load.path = function (dir) {
  dir = path.resolve(dir || '.')

  try {
    var name = runtimeRequire(path.join(dir, 'package.json')).name.toUpperCase().replace(/-/g, '_')
    if (process.env[name + '_PREBUILD']) dir = process.env[name + '_PREBUILD']
  } catch (err) {}

  if (!prebuildsOnly) {
    var release = getFirst(path.join(dir, 'build/Release'), matchBuild)
    if (release) return release

    var debug = getFirst(path.join(dir, 'build/Debug'), matchBuild)
    if (debug) return debug
  }

  var prebuild = resolve(dir)
  if (prebuild) return prebuild

  var nearby = resolve(path.dirname(process.execPath))
  if (nearby) return nearby

  var target = [
    'platform=' + platform,
    'arch=' + arch,
    'runtime=' + runtime,
    'abi=' + abi,
    'uv=' + uv,
    armv ? 'armv=' + armv : '',
    'libc=' + libc,
    'node=' + process.versions.node,
    process.versions.electron ? 'electron=' + process.versions.electron : '',
    typeof __webpack_require__ === 'function' ? 'webpack=true' : '' // eslint-disable-line
  ].filter(Boolean).join(' ')

  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')

  function resolve (dir) {
    // Find matching "prebuilds/<platform>-<arch>" directory
    var tuples = readdirSync(path.join(dir, 'prebuilds')).map(parseTuple)
    tuples.forEach(t => console.log(`Found tuple: ${t.name} with arch ${t.architectures} and platform ${t.platform}`))
    if (armv === "default") armv = "7"
    console.log("Looking for tuple with platform " + platform + " and arch " + arch + " abi " + abi + " runtime " + runtime + " uv " + uv + " armv " + armv + " libc " + libc)
    var tuple = tuples.filter(matchTuple(platform, arch)).sort(compareTuples)[0]
    if (!tuple) return

    // Find most specific flavor first
    var prebuilds = path.join(dir, 'prebuilds', tuple.name)
    var parsed = readdirSync(prebuilds).map(parseTags)
    parsed.forEach(p => console.log(`Found prebuild: ${p.file} with tags ${JSON.stringify(p)}`))
    var candidates = parsed.filter(matchTags(runtime, abi))
    var winner = candidates.sort(compareTags(runtime))[0]
    if (winner) console.log(`going to call require with: ${path.join(prebuilds, winner.file)}`)
    if (winner) return path.join(prebuilds, winner.file)
  }
}

function readdirSync (dir) {
  try {
    return fs.readdirSync(dir)
  } catch (err) {
    return []
  }
}

function getFirst (dir, filter) {
  var files = readdirSync(dir).filter(filter)
  return files[0] && path.join(dir, files[0])
}

function matchBuild (name) {
  return /\.node$/.test(name)
}

function parseTuple (name) {
  // Example: darwin-x64+arm64
  var arr = name.split('-')
  if (arr.length !== 2) return

  var platform = arr[0]
  var architectures = arr[1].split('+')

  if (!platform) return
  if (!architectures.length) return
  if (!architectures.every(Boolean)) return

  return { name, platform, architectures }
}

function matchTuple (platform, arch) {
  return function (tuple) {
    if (tuple == null) return false
    if (tuple.platform !== platform) return false
    return tuple.architectures.includes(arch)
  }
}

function compareTuples (a, b) {
  // Prefer single-arch prebuilds over multi-arch
  return a.architectures.length - b.architectures.length
}

function parseTags (file) {
  var arr = file.split('.')
  var extension = arr.pop()
  var tags = { file: file, specificity: 0 }

  if (extension !== 'node') return

  for (var i = 0; i < arr.length; i++) {
    var tag = arr[i]

    if (tag === 'node' || tag === 'electron' || tag === 'node-webkit') {
      tags.runtime = tag
    } else if (tag === 'napi') {
      tags.napi = true
    } else if (tag.slice(0, 3) === 'abi') {
      tags.abi = tag.slice(3)
    } else if (tag.slice(0, 2) === 'uv') {
      tags.uv = tag.slice(2)
    } else if (tag.slice(0, 4) === 'armv') {
      tags.armv = tag.slice(4)
    } else if (tag === 'glibc' || tag === 'musl') {
      tags.libc = tag
    } else {
      continue
    }

    tags.specificity++
  }

  return tags
}

function matchTags (runtime, abi) {
  return function (tags) {
    if (tags == null) return false
    if (tags.runtime !== runtime && !runtimeAgnostic(tags)) return false
    if (tags.abi !== abi && !tags.napi) return false
    if (tags.uv && tags.uv !== uv) return false
    if (tags.armv && tags.armv !== armv) return false
    if (tags.libc && tags.libc !== libc) return false

    return true
  }
}

function runtimeAgnostic (tags) {
  return tags.runtime === 'node' && tags.napi
}

function compareTags (runtime) {
  // Precedence: non-agnostic runtime, abi over napi, then by specificity.
  return function (a, b) {
    if (a.runtime !== b.runtime) {
      return a.runtime === runtime ? -1 : 1
    } else if (a.abi !== b.abi) {
      return a.abi ? -1 : 1
    } else if (a.specificity !== b.specificity) {
      return a.specificity > b.specificity ? -1 : 1
    } else {
      return 0
    }
  }
}

function isNwjs () {
  return !!(process.versions && process.versions.nw)
}

function isElectron () {
  if (process.versions && process.versions.electron) return true
  if (process.env.ELECTRON_RUN_AS_NODE) return true
  return typeof window !== 'undefined' && window.process && window.process.type === 'renderer'
}

function isAlpine (platform) {
  return platform === 'linux' && fs.existsSync('/etc/alpine-release')
}

// Exposed for unit tests
// TODO: move to lib
load.parseTags = parseTags
load.matchTags = matchTags
load.compareTags = compareTags
load.parseTuple = parseTuple
load.matchTuple = matchTuple
load.compareTuples = compareTuples
```

**Comment by DaniRey** [comment]
This might be related to https://github.com/astefanutti/scratch-node/issues/3

**Comment by DaniRey** [comment]
I also wanted to make sure the problem is not related to any difference between loading files from within the package versus from the actual filesystem.

Therefore I went back to the default logic, which expects an "armdefault" instead of "armv7" prebuild and provided it from the process.execPath. It results in the same error.

```
going to call require with: /home/solar21/Desktop/prebuilds/linux-arm/node.napi.armdefault.node
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Dynamic loading not supported
    at process.dlopen (pkg/prelude/bootstrap.js:2256:28)
    at Module._extensions..node (node:internal/modules/cjs/loader:1719:18)
    at Module.load (node:internal/modules/cjs/loader:1322:32)
    at Module._load (node:internal/modules/cjs/loader:1132:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1344:12)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/helpers:141:16)
    at load (/snapshot/pkg_serialport_friendship/node_modules/node-gyp-build/node-gyp-build.js:22:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by robertsLando** [comment]
@DaniRey AFAIK dlopen error happens exactly when you try to load a node native addon from the snapshot, what we do [here](https://github.com/yao-pkg/pkg/blob/main/prelude/bootstrap.js#L2204) is to catch the dlopen request, copy the binary to a local fs folder and serve it from there. I sincerely have no clue why this happens BTW, could it be that the node binary you are using is not the correct one?

**Comment by DaniRey** [comment]
@robertsLando Interesting. But shouldn't it then work anyway,when I load from the filesytem, like in the last test I did?

We never got it running with yao-pkg on RaspberryPi. But we can run it when using a locally installed node (which we would like to avoid).

My understanding is, we have an armv7 processor, and it is compatible with armv6. I repeated my last test with the armv6 prebuild, it fails with "Dynamic loading not supported", like it does with armv6.

I tried a require in the locally installed node. It seems to be happy with both prebuils.
```

> require("/home/solar21/Desktop/prebuilds/linux-arm/node.napi.armv7");
{
  set: [Function (anonymous)],
  get: [Function (anonymous)],
  getBaudRate: [Function (anonymous)],
  open: [Function (anonymous)],
  update: [Function (anonymous)],
  close: [Function (anonymous)],
  flush: [Function (anonymous)],
  drain: [Function (anonymous)],
  Poller: [Function: Poller]
}
> require("/home/solar21/Desktop/prebuilds/linux-arm/node.napi.armv6");
{
  set: [Function (anonymous)],
  get: [Function (anonymous)],
  getBaudRate: [Function (anonymous)],
  open: [Function (anonymous)],
  update: [Function (anonymous)],
  close: [Function (anonymous)],
  flush: [Function (anonymous)],
  drain: [Function (anonymous)],
  Poller: [Function: Poller]
}
```

**Comment by DaniRey** [comment]
@robertsLando I added some debug information to bootstrap.js and the patch of dlopen does what it should do.

```
going to call require with: /snapshot/pkg_serialport_friendship/node_modules/@serialport/bindings-cpp/prebuilds/linux-arm/node.napi.armv7.node
Patched dlopen in charge of loading native modules
dlopen /snapshot/pkg_serialport_friendship/node_modules/@serialport/bindings-cpp/prebuilds/linux-arm/node.napi.armv7.node, which has is inside snapshot
dlopen [object process] /home/solar21/.cache/pkg/0f3fc12ed86fb8ea6460c7d2b612db997bd0bb6c8a6eb7492f93dcad376c7cea/@serialport/bindings-cpp/prebuilds/linux-arm/node.napi.armv7.node



pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Dynamic loading not supported
    at process.dlopen (pkg/prelude/bootstrap.js:2260:28)
    at Module._extensions..node (node:internal/modules/cjs/loader:1719:18)
    at Module.load (node:internal/modules/cjs/loader:1322:32)
    at Module._load (node:internal/modules/cjs/loader:1132:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1344:12)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/helpers:141:16)
    at load (/snapshot/pkg_serialport_friendship/node_modules/node-gyp-build/node-gyp-build.js:22:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v22.10.0
```

Also the file in the cache is valid

```
node
Welcome to Node.js v20.18.3.
Type ".help" for more information.
> require("/home/solar21/.cache/pkg/0f3fc12ed86fb8ea6460c7d2b612db997bd0bb6c8a6eb7492f93dcad376c7cea/@serialport/bindings-cpp/prebuilds/linux-arm/node.napi.armv7.node")
{
  set: [Function (anonymous)],
  get: [Function (anonymous)],
  getBaudRate: [Function (anonymous)],
  open: [Function (anonymous)],
  update: [Function (anonymous)],
  close: [Function (anonymous)],
  flush: [Function (anonymous)],
  drain: [Function (anonymous)],
  Poller: [Function: Poller]
}
```

**Comment by robertsLando** [comment]
> I will now try to build a "regular" alpine node version for armv7, instead of the linuxstatic version.

Ooooh I completely missed that, sorry! Yeah linux static cannot use native addons, at start by reading your issues I thought it used to work on your side and stopped working with latest. Sorry for the misunderstanding.

I personally use this binaries: https://github.com/yao-pkg/pkg-binaries

**Comment by robertsLando** [comment]
And here is a repo where you can see them in action: https://github.com/zwave-js/zwave-js-ui/blob/master/.github/workflows/package_armv7.yml#L48

**Comment by DaniRey** [comment]
@robertsLando Thank you for your help. I've got it running for my original project 🥳
